### ISSUE TITLE
[FEATURE]: Login page design

### ISSUE THREAD

**Issue by nexel-dev** [sital002/foodhub#1]
Make a login page where user will be able to sign in via email and password or third party such as google or facebook.
Here are some of the reference images:
![login-form-5-free-bootstrap-login-forms](https://github.com/sital002/foodhub/assets/93700622/71bf7413-bbb1-40cc-95d5-991cc30f135b)
<img width="300" alt="sign-in-with-password" src="https://github.com/sital002/foodhub/assets/93700622/e3b0c405-da8b-491b-aadc-bc1726a937ea">

**Comment by saroj018** [comment]
can i work on this
